### ISSUE TITLE
Adjustable sizes on the input box

### ISSUE THREAD

**Issue by rwmoose** [six-two/mkdocs-placeholder-plugin#10]
First of all, I love this plugin.  

I've got some long strings I'm using (up to 50 characters), and they exceed width of the input boxes.  I tried updating the css but no luck. Any suggestions?

**Comment by six-two** [comment]
Hi, how are you creating the input boxes? Are you using placeholder tables, inline editors, or custom text boxes?

**Comment by six-two** [comment]
Assuming that you mean placeholder tabes, you should be able to do something like the following in CSS:
```css
.auto-input-table input,
.auto-input-table select {
    width: 50em;
}
```
`50em` seems a little to big, since in smaller windows it overlaps with the side bar.

You could also manually create input fields with `<input class="some-custom-class-for-styling" data-input-for="PLACEHOLDER_NAME">` and then style them. If you put the labels above the text input, then you should be able to make them use the full content width without layout problems:
```css
.some-custom-class-for-styling {
    width: 100%;
}
```

I added a test page ([source](https://raw.githubusercontent.com/six-two/mkdocs-placeholder-plugin/refs/heads/main/docs/tests/auto-tables-wide.md), [rendered](https://dev.mkdocs-placeholder-plugin.six-two.dev/tests/auto-tables-wide/) that uses both stylings described in this comment. Does this solve your issue?
