### ISSUE TITLE
Feature Request: Allow customizing the automatic placeholder tables

### ISSUE THREAD

**Issue by MattTheCuber** [six-two/mkdocs-placeholder-plugin#8]
Allow customizing this (text, color, settings, etc.):

![image](https://github.com/six-two/mkdocs-placeholder-plugin/assets/32849887/3c86fde6-5a1e-40c8-a692-60e513adfaca)

**Comment by six-two** [comment]
I think you can style it via CSS already. You just need to make your rules more specific than the default CSS that ships with the plugin. For example if I define a rule for `.auto-input-table`, you can define a rule for `body .auto-input-table` and overwrite my settings. Then you include your CSS file, by adding something like the following in your `mkdocs.yaml`:

```yaml
extra_css:
    - path/to/your-custom-style.css
```

You can find the default styles at <https://github.com/six-two/mkdocs-placeholder-plugin/blob/main/src/mkdocs_placeholder_plugin/generic/generic_style.py>. Everything containing the class `auto-input-table` is related to automatically generated placeholder tables.

Does this work for you?

**Comment by MattTheCuber** [comment]
```css
body .auto-input-table {
    border-color: var(--md-primary-fg-color);
}
body .auto-input-table .auto-table-title {
    background-color: var(--md-primary-fg-color);
}

.auto-input-table .auto-table-title .settings_button {
    display: none;
}

.auto-input-table .expandable_contents .table-div b {
    display: none;
}
.auto-input-table .expandable_contents .table-div::before {
    margin: 3px auto 10px auto;
    padding: 0px 5px;
    content: "Please update and verify the following fields, then press Enter.";
} 
```

Not super pretty, but this worked! Thank you for the information.
