### ISSUE TITLE
InnerHTML replace mode breaks the search

### ISSUE THREAD

**Issue by websolutions-hamburg** [six-two/mkdocs-placeholder-plugin#9]
Hello,
when I use the InnerHTML replace mode, the search from mkdocs material is broken. It no longer opens.

**Requirements:**

```log
mkdocs                            1.6.1
mkdocs-material                   9.6.5
mkdocs-placeholder-plugin         0.5.0.post1
```

**placeholder.yml**

```yaml
placeholders:
  FIRST_NAME:
    default: John
    replace_everywhere: true
```

**mkdocs.yml**

```yaml
site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material

plugins:
  - search
  - placeholder:
      enabled: true
      placeholder_file: placeholder.yml
```

index.md

```markdown
# Welcome to MkDocs

iFIRST_NAMEi
```

<br>

When I use `iFIRST_NAMEi` it's broken.
When I use `xFIRST_NAMEx` everything is fine.
